1.
Write a function to find the maximum of three numbers and return the result.

In [8]:
def maximum(n1,n2,n3):
    if n1>n2 and n1>n3:
        print(f'Maximum value : {n1}')
    elif n2>n1 and n2>n3:
        print(f'Maximum value : {n2}')
    else:
        print(f'Maximum value : {n3}')
n1=int(input("Enter first number : "))
n2=int(input("Enter second number : "))
n3=int(input("Enter third number : "))
maximum(n1,n2,n3)

Enter first number : 2
Enter second number : 6
Enter third number : 8
Maximum value : 8


2.
Implement a function to calculate the area of a circle given the radius

In [14]:
def area(r):
  circle_area=3.14*r**2
  print(f"area of a circle:{circle_area}")
r=float(input("radius:"))
area(r)



radius:3
area of a circle:28.26


3.Create a function to check if a given number is prime or not, and return a boolean result.

In [15]:
def prime(n):
    for i in range(2,n):
        if n%i==0:
            return False
    else:
        return True
n=int(input("Enter a number : "))
prime(n)

Enter a number : 7


True

4.Create a function to check if a given string is a palindrome and return a boolean result

In [41]:
def palindrome(string):
    if string==string[::-1]:
        return True
    else:
        return False
string=input("Enter the string : ")
palindrome(string)

Enter the string : 2


True

5.Implement a function to calculate the sum of all numbers in a list and return the sum.

In [42]:
def sum_of_all(list1):
    sum=0
    for i in list1:
        sum+=i
    return sum
list1=[4,7,1,9,3]
print(list1)
sum_of_all(list1)

[4, 7, 1, 9, 3]


24

6.Create a function to find the average of a list of numbers and return the average value.

In [43]:
def average(list2):
    sum=0
    for i in list2:
        sum+=i
    avg=sum/len(list2)
    return avg
list2=[5,1,3,4,5]
average(list2)

3.6

7.Write a function to find the kth largest element in an unsorted list.





In [20]:
def kth_largest(list3,k):
    list3.sort(reverse=True)
    print(f'{k}th largest element : {list3[k-1]}' )
list3=[1,2,3,4,5]
k=3
print(list3)
kth_largest(list3,k)

[1, 2, 3, 4, 5]
3th largest element : 3


8.Write a recursive function to find the sum of digits of a positive integer.

In [21]:
def sum_of_digits(integer):
    if integer<10:
        return integer
    else:
        return integer%10 + sum_of_digits(integer//10)
integer=2134
sum_of_digits(integer)

10

9.Write a recursive function to calculate the power of a number.

In [22]:
def power_of_number(base,exp):
    if exp==0:
        return 1
    else:
        for i in range(exp):
            return base*power_of_number(base,exp-1)
base=int(input("Enter base value : "))
exp=int(input("Enter exponent value : "))
powr=power_of_number(base,exp)
print(f'Power of the number : {powr}')

Enter base value : 6
Enter exponent value : 2
Power of the number : 36


10.Create a function to find the greatest common divisor (GCD) of two numbers using Euclidean algorithm.

In [23]:
def gcd(a,b):
    while b!=0:
        a,b=b,a%b
    return a
a=int(input("Enter first number : "))
b=int(input("Enter second number : "))
print(f"Greatest common divisor of {a} and {b} : {gcd(a,b)}")

Enter first number : 5
Enter second number : 2
Greatest common divisor of 5 and 2 : 1


11.Create a 1D array of numbers from 0 to 9.

In [25]:
import numpy as np
arr1=np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

12.Create a 2D array of shape (3, 3) with values ranging from 1 to 9.




In [26]:
arr2=np.arange(1,10)
arr2=arr2.reshape(3,3)
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

13.Create a 3x3 identity matrix.

In [27]:
arr3=np.eye(3)
arr3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14.Create an array of 10 random numbers and find the mean and standard deviation.

In [28]:
arr4=np.random.randint(10,101,10)
print(arr4)
print(f"mean : {arr4.mean()}")
print(f"standard deviation : {arr4.std()}")

[34 68 81 15 26 47 72 56 77 34]
mean : 51.0
standard deviation : 22.013632140108093


15.Create a 1D array of numbers from 10 to 20 and extract the first 5 elements.

In [29]:
arr5=np.arange(10,21)
arr5

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

16.Create a 2D array of shape (4, 4) and extract the second row.

In [34]:
arr6=np.arange(2,33,2)
arr6=arr6.reshape(4,4)
arr6

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

In [35]:
arr6[1]

array([10, 12, 14, 16])

17.Create two 1D arrays of length 5 with values ranging from 1 to 5 and 6 to 10. Perform element-wise addition.

In [36]:
arr7=np.arange(1,6)
arr7


array([1, 2, 3, 4, 5])

In [37]:
arr8=np.arange(6,11)
arr8

array([ 6,  7,  8,  9, 10])

In [38]:
arr=arr7+arr8
arr

array([ 7,  9, 11, 13, 15])

18.Create a 1D array of 10 random numbers and replace all elements less than 0.5 with 0.

In [39]:
arr9=np.random.rand(10)
arr9

array([0.45802712, 0.86117594, 0.72392168, 0.19839831, 0.62084674,
       0.59203386, 0.64815957, 0.51189553, 0.36105411, 0.18035374])

In [40]:
arr9[arr9<0.5]=0
arr9


array([0.        , 0.86117594, 0.72392168, 0.        , 0.62084674,
       0.59203386, 0.64815957, 0.51189553, 0.        , 0.        ])